name: Deploy static site to HostGator (SFTP)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- SSH key authentication (recommended) ---
      # Required repo secrets:
      #   SFTP_HOST, SFTP_USERNAME, SSH_PRIVATE_KEY, SFTP_TARGET_DIR
      # Optional: SFTP_PORT (defaults to 22 if omitted)
      - name: Deploy via SFTP (SSH key)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          # omit 'port' to use default 22, or set it if your host uses a custom port:
          # port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          sftp_only: true
          local_path: './'
          remote_path: ${{ secrets.SFTP_TARGET_DIR }}
          # Use rsync-style excludes supported by this action:
          rsyncArgs: >-
            --exclude=.git
            --exclude=.github
            --exclude=README.md
            --exclude=LICENSE
            --exclude=**/.DS_Store
